### ISSUE TITLE
[Feature Request] Use Google Calendar API to fetch the data

### ISSUE THREAD

**Issue by arnabsen1729** [debojeetjha10/whatsapp_notifier_of_classes_XD#1]
Instead of fetching the data from static JSON file, you can use Calendar API to fetch the data from the Calendar, that way any further changes in the schedule will be accounted as well. 

Ref : [Google Docs](https://developers.google.com/calendar/v3/reference)

**Comment by debojeetjha10** [comment]
ok!! @arnabsen1729  working on it!!!
[This](https://developers.google.com/calendar/concepts/events-calendars) one ri8?
